### ISSUE TITLE
Using `const` flag results in build errors

### ISSUE THREAD

**Issue by AlexanderAmelkin** [openbmc/sdbusplus#30]
If `const` flag is used as described in [interface.md](https://github.com/openbmc/sdbusplus/blob/596a223c2f0b9f6577f79f8036774aae88180268/docs/interface.md):

> The only current supported value for flags is const, which corresponds to SD_BUS_VTABLE_PROPERTY_CONST, making the property read-only via D-Bus but still writable by the app implementing it.

then build fails like this:

```
| Traceback (most recent call last):
|   File "/home/spirit/src/vesnin/openbmc-alternate/build/tmp/work/armv5e-openbmc-linux-gnueabi/phosphor-dbus-interfaces/1.0-r1/recipe-sysroot-native/usr/bin/sdbus++", line 50, in <module>
|     main()
|   File "/home/spirit/src/vesnin/openbmc-alternate/build/tmp/work/armv5e-openbmc-linux-gnueabi/phosphor-dbus-interfaces/1.0-r1/recipe-sysroot-native/usr/bin/sdbus++", line 45, in main
|     instance = valid_types[args.typeName].load(args.item, args.rootdir)
|   File "/home/spirit/src/vesnin/openbmc-alternate/build/tmp/work/armv5e-openbmc-linux-gnueabi/phosphor-dbus-interfaces/1.0-r1/recipe-sysroot-native/usr/lib/python2.7/site-packages/sdbusplus/interface.py", line 21, in load
|     return Interface(**y)
|   File "/home/spirit/src/vesnin/openbmc-alternate/build/tmp/work/armv5e-openbmc-linux-gnueabi/phosphor-dbus-interfaces/1.0-r1/recipe-sysroot-native/usr/lib/python2.7/site-packages/sdbusplus/interface.py", line 25, in __init__
|     [Property(**p) for p in kwargs.pop('properties', [])]
|   File "/home/spirit/src/vesnin/openbmc-alternate/build/tmp/work/armv5e-openbmc-linux-gnueabi/phosphor-dbus-interfaces/1.0-r1/recipe-sysroot-native/usr/lib/python2.7/site-packages/sdbusplus/property.py", line 12, in __init__
|     super(Property, self).__init__(**kwargs)
|   File "/home/spirit/src/vesnin/openbmc-alternate/build/tmp/work/armv5e-openbmc-linux-gnueabi/phosphor-dbus-interfaces/1.0-r1/recipe-sysroot-native/usr/lib/python2.7/site-packages/sdbusplus/namedelement.py", line 8, in __init__
|     super(NamedElement, self).__init__(**kwargs)
|   File "/home/spirit/src/vesnin/openbmc-alternate/build/tmp/work/armv5e-openbmc-linux-gnueabi/phosphor-dbus-interfaces/1.0-r1/recipe-sysroot-native/usr/lib/python2.7/site-packages/sdbusplus/renderer.py", line 3, in __init__
|     super(Renderer, self).__init__(**kwargs)
| TypeError: object.__init__() takes no parameters
```
Specifically, the failure is triggered by this code block in a yaml interface file:

```
properties:
    - name: Whatever
      type: boolean
      default: false
      flags:
        - const
```

If I remove the `flags`, then phosphor-dbus-interfaces builds just fine.

**Comment by wak-google** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/sdbusplus/+/21686

**Comment by AlexanderAmelkin** [comment]
This fixed build for me. Thanks.

**Comment by AlexanderAmelkin** [comment]
@wak-google, @geissonator, although `phosphor-dbus-interfaces` now builds just fine with `flags: - const`, the properties that I defined as `const` can still easily be updated by third party. The interface I defined is implemented by phosphor-settings and I can change those `const` properties via REST. Is that an expected behavior?
